Adding application structure for alpha branch
prasadtalasila/TransportScheduler pull request #108
Opened 2018-03-31 19:22 UTC by bgargi

Application structure for alpha branch-individual dummy server applications on which the main (dummy) TS application depends. 

Motivation - Compliance with OTP standards.

2018-04-02 15:32 UTC, prasadtalasila commented
@SuhasHebbar and @suryapratapmehra This PR introduces the mix application structure into the project. Both of you encouraged to download and run the code base to verify the broad structure that has been put in place.

This PR has to be analysed in light of the information put on [Build with mix](https://github.com/prasadtalasila/TransportScheduler/wiki/CS-Build-with-Mix) wiki page and the example [application structure](https://github.com/prasadtalasila/TransportScheduler/tree/benchmarks/application_structure) directory of the benchmarks branch.

Please complete your review by 10:30AM, 3-April-2018 so that we can move the discussion forward with @bgargi. Thanks.

2018-04-02 18:20 UTC, prasadtalasila requested changes
@bgargi please see the suggested changes.

2018-04-02 18:20 UTC, prasadtalasila commented on ts_app_struct/api/.gitignore
> +# The directory Mix will write compiled artifacts to.
It's better to move the contents of `ts_app_struct` to top level. The existing top-level contents of transportscheduler project would go into one of the three projects, namely input_parser, network, and api.

2018-04-02 18:20 UTC, prasadtalasila commented on ts_app_struct/api/mix.exs
> +      {:network_constructor,  path: "/home/bgargi/Videos/network_constructor"},
This has to reference to the local instance of network application.

2018-04-02 18:20 UTC, prasadtalasila commented on ts_app_struct/network_constructor/.gitignore
> +# The directory Mix will write compiled artifacts to.
This application can just be called `network` instead of `network_constructor`

2018-04-02 18:20 UTC, prasadtalasila commented on ts_app_struct/network_constructor/config/config.exs
> +#     import_config "#{Mix.env}.exs"
It is better to have stand alone configurations for each of the applications. These configs help us test the applications on a stand alone basis and in integration with other dependencies.

2018-04-02 18:20 UTC, prasadtalasila commented on ts_app_struct/api/config/config.exs
> +#     import_config "#{Mix.env}.exs"
It is better to have stand alone config to enable stand alone and integration tests.

2018-04-02 18:20 UTC, prasadtalasila commented on ts_app_struct/network_constructor/mix.exs
> +      {:input_parser,  path: "/home/bgargi/Videos/input_parser"},
again the path has to be relative to the code base and must be valid under all execution environments.

2018-04-02 18:20 UTC, prasadtalasila commented on ts_app_struct/transport_scheduler/.gitignore
> +# The directory Mix will write compiled artifacts to.
If possible, we can have this as the default application at the top-level, with the other three being dependencies. If Elixir allows tucking in of dependencies to a sub-directory, say `deps`, then we can put `input_parser, network, api` into `deps` directory.

Done this way, the top-level looks like one single Elixir project with some dependencies.

2018-04-03 05:43 UTC, prasadtalasila commented
The suggested application structure is as follows.
```bash
config/
dependencies/
    input_parser/
        ...elixir project structure
    network/
        ...elixir project structure
    api/
        ...elixir project structure
    util/
         ...util elixir modules only (not a project)
lib/
    ts.ex
    ts/application.ex
test
    test_helper.ex
    ts_test.ex
```

2018-04-03 05:46 UTC, bgargi commented
https://8thlight.com/blog/georgina-mcfadyen/2017/05/01/elixir-umbrella-projects.html

2018-04-03 05:50 UTC, prasadtalasila commented
http://learningelixir.joekain.com/designing-with-otp-applications-in-elixir/

2018-04-09 14:09 UTC, prasadtalasila commented
Please open a fresh PR for the umbrella project structure. Closing this PR.

2018-04-09 14:09 UTC, closed without merging